### ISSUE TITLE
Error on restore sessions

### ISSUE THREAD

**Issue by zshamrock** [zshamrock/dynoman#224]
```
java.lang.NullPointerException
	at com.akazlou.dynoman.service.SearchesSaverService.restore(SearchesSaverService.kt:160)
	at com.akazlou.dynoman.controller.SessionSaverController.restore(SessionSaverController.kt:25)
	at com.akazlou.dynoman.view.QueryView$root$1$controlArea$1$5$2$1.invoke(QueryView.kt:98)
	at com.akazlou.dynoman.view.QueryView$root$1$controlArea$1$5$2$1.invoke(QueryView.kt:25)
	at tornadofx.AsyncKt$runAsyncWithProgress$3.invoke(Async.kt:248)
	at tornadofx.AsyncKt$runAsyncWithProgress$3.invoke(Async.kt)
	at tornadofx.FXTask.call(Async.kt:457)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by zshamrock** [comment]
Using "Migrations" session.
